// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: protofiles/list_orders.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ListOrdersService_ListOrders_FullMethodName = "/pb.ListOrdersService/ListOrders"
)

// ListOrdersServiceClient is the client API for ListOrdersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ListOrdersServiceClient interface {
	ListOrders(ctx context.Context, in *Blank, opts ...grpc.CallOption) (*ListOrdersResponse, error)
}

type listOrdersServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewListOrdersServiceClient(cc grpc.ClientConnInterface) ListOrdersServiceClient {
	return &listOrdersServiceClient{cc}
}

func (c *listOrdersServiceClient) ListOrders(ctx context.Context, in *Blank, opts ...grpc.CallOption) (*ListOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOrdersResponse)
	err := c.cc.Invoke(ctx, ListOrdersService_ListOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListOrdersServiceServer is the server API for ListOrdersService service.
// All implementations must embed UnimplementedListOrdersServiceServer
// for forward compatibility.
type ListOrdersServiceServer interface {
	ListOrders(context.Context, *Blank) (*ListOrdersResponse, error)
	mustEmbedUnimplementedListOrdersServiceServer()
}

// UnimplementedListOrdersServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedListOrdersServiceServer struct{}

func (UnimplementedListOrdersServiceServer) ListOrders(context.Context, *Blank) (*ListOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOrders not implemented")
}
func (UnimplementedListOrdersServiceServer) mustEmbedUnimplementedListOrdersServiceServer() {}
func (UnimplementedListOrdersServiceServer) testEmbeddedByValue()                           {}

// UnsafeListOrdersServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ListOrdersServiceServer will
// result in compilation errors.
type UnsafeListOrdersServiceServer interface {
	mustEmbedUnimplementedListOrdersServiceServer()
}

func RegisterListOrdersServiceServer(s grpc.ServiceRegistrar, srv ListOrdersServiceServer) {
	// If the following call pancis, it indicates UnimplementedListOrdersServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ListOrdersService_ServiceDesc, srv)
}

func _ListOrdersService_ListOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Blank)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListOrdersServiceServer).ListOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ListOrdersService_ListOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListOrdersServiceServer).ListOrders(ctx, req.(*Blank))
	}
	return interceptor(ctx, in, info, handler)
}

// ListOrdersService_ServiceDesc is the grpc.ServiceDesc for ListOrdersService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ListOrdersService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ListOrdersService",
	HandlerType: (*ListOrdersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListOrders",
			Handler:    _ListOrdersService_ListOrders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protofiles/list_orders.proto",
}
